# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default=b'picture', max_length=320),
        ),
    ]
